# Generated by Django 5.1.2 on 2024-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewModelDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dt_birth', models.DateField()),
                ('comment', models.TextField()),
                ('change_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
